import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ButtonLink from "../../componant/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 pt-3  gap-4">
          <ButtonLink />
        </div>
        <div className="flex-1 ml-4 ">{children}</div>
      </body>
    </html>
  );
}
